"""project private

Revision ID: 8fae2b8d7b33
Revises: 9150d53f56ef
Create Date: 2020-10-02 01:30:09.762172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fae2b8d7b33'
down_revision = '9150d53f56ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'starred')
    op.drop_column('project', 'private')
    # ### end Alembic commands ###
