"""user-update

Revision ID: 90107ef2ac86
Revises: dab856925de9
Create Date: 2020-10-02 22:43:38.230023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90107ef2ac86'
down_revision = 'dab856925de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_language')
    op.drop_column('user_privileges', 'is_super_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_privileges', sa.Column('is_super_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('preferred_language', mysql.VARCHAR(length=4), nullable=True))
    # ### end Alembic commands ###
