"""project category

Revision ID: 9150d53f56ef
Revises: 5e18cea7343a
Create Date: 2020-10-01 22:22:21.155950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9150d53f56ef'
down_revision = '5e18cea7343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('category', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'category')
    # ### end Alembic commands ###
