"""project github

Revision ID: dab856925de9
Revises: 8fae2b8d7b33
Create Date: 2020-10-02 12:36:46.171313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab856925de9'
down_revision = '8fae2b8d7b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_url', sa.String(length=200), nullable=True))
    op.add_column('project', sa.Column('website_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'website_url')
    op.drop_column('project', 'github_url')
    # ### end Alembic commands ###
